---

matrix:
  include:
    - os: osx
      osx_image: xcode12
      language: generic

before_install:
  - brew update
  - wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py

install:
  - ansible-galaxy install --force git+https://github.com/deekayen/ansible-role-summon.git,${TRAVIS_COMMIT}
  - brew install ansible-lint
  - sudo python /tmp/get-pip.py
  - sudo pip install yamllint

before_script:
  - yamllint --version
  - ansible-lint --version
  - ansible --version

script:
  - yamllint .
  - ansible-lint --exclude=/Users/travis/.ansible/roles .
  - ansible-playbook --syntax-check --list-tasks -i 127.0.0.1, tests/test.yml
  - ansible-playbook --check --diff -i 127.0.0.1, -c local tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
